### ISSUE TITLE
Support promises

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/ware#24]
I'd like to use this in a project that is using promises internally, it would be great if sync functions that return a `Promise` (or any then-able) could be treated as async.

**Comment by 486** [comment]
Hi, ware does this already. Have a look at the tests.

**Comment by dominicbarnes** [comment]
:D

**Comment by dominicbarnes** [comment]
Note added in 132e961cae2f7d87842fd3a8e0bf540e5ad4f7c9
